### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by scientificworld** [airingursb/airing-translator#5]
=== 🍻  欢迎使用 Airing 翻译小助手 🍻  ===
apple 的翻译结果为：
/usr/local/lib/node_modules/airing-translator/index.js:45
      console.log(JSON.parse(data).trans_result[0].dst);
                                               ^

TypeError: Cannot read property '0' of undefined
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/airing-translator/index.js:45:48)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.Readable.read (_stream_readable.js:486:10)
    at flow (_stream_readable.js:922:34)
    at resume_ (_stream_readable.js:904:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by airingursb** [comment]
api 的密钥过期了，需要换一副了
